[package]
name = "basics"
version = "0.1.0"
authors = ["Warlock <b.jurczok@gmail.com>"]
edition = "2018"
homepage = "me.org"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
